token: "$LICHESS_TOKEN"
url: "https://lichess.org/"

engine:
  dir: "./src/"
  name: "Ethereal"
  protocol: "uci"
  uci_options:
    Threads: 1
    Hash: 512
    MoveOverhead: 500
    Ponder: false
    SyzygyPath: "./syzygy"
    SyzygyProbeDepth: 1

# --- SOSYAL AYARLAR ---
chat:
  welcome: "Hi! Void v3 active. Tournament & Matchmaking mode enabled. Be ready!"
  goodbye: "GG! See you later."

# --- SAVAŞ MODU (GELEN MEYDAN OKUMALAR) ---
challenge_policy:
  accept_bot: true
  accept_human: true
  rated: true
  time_controls:
    - bullet
    - blitz
    - rapid
    - classical
  min_time: 60
  max_time: 2000

# --- MATCHMAKING & TURNUVA (HYBRID) ---
matchmaking:
  allow_feed: true
  challenge_interval: 60
  challenge_timeout: 30
  max_games: 2
  
  # --- Turnuva Ayarları ---
  auto_tournament: true
  join_upcoming_mins: 15
  only_bot_tourneys: true
  
  # --- ELO KORUMA FİLTRESİ ---
  opponent_min_rating: 1500
  opponent_max_rating: 4000
  opponent_rating_difference: 700

  time_controls:
    - "1+0"
    - "1+1"
    - "2+1"
    - "3+0"
    - "3+2"
    - "5+0"
    - "5+2"
    - "10+0"
    - "10+2"
    - "30+0"
    
  challenge_bots: true
  challenge_humans: false
  selection: "random"
